### ISSUE TITLE
Eth wallet RPC url

### ISSUE THREAD

**Issue by dxnght** [nervosnetwork/godwoken-info#15]
Please add to README next line:

Eth-wallet (i.e. Metamask) RPC URL: "https://mainnet.godwoken.io/rpc/eth-wallet"

It is used to show the actual Godwoken CKB balance inside i.e. Metamask wallet

I'm using Metamask chrome extension

You will see next result:
![image](https://user-images.githubusercontent.com/33819269/152145017-642b28e8-0a66-4a05-bf12-8f0aebc21583.png)

**Comment by Flouse** [comment]
Added into the infos of Godwoken testnet_v1
- https://github.com/nervosnetwork/godwoken-info/pull/16/files#diff-0b45e34d58832d8183c8661473eab29e73d670cf7341ca362cba5ce138284c76R17
