### ISSUE TITLE
Web3 Indexer Error: user log data size too large: 8460

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/godwoken-info#30]
This error is being reported by our node partner GetBlock that is trying to setup a Godwoken v1 testnet node. I've also been receiving this same error locally.

![image (45)](https://user-images.githubusercontent.com/37931/171236497-114d08ba-dc7f-485f-bc4f-4231aab2d4c8.png)

**Comment by Flouse** [comment]
Please use the latest image of web3-indexer in this PR:
https://github.com/nervosnetwork/godwoken-info/pull/29/files#diff-929da18bc4dbfbf6b1fe37b239d522b67c86e89986b55cb8986947f28e1b280fR73

## Tested in the GitHub Action workflow
https://github.com/nervosnetwork/godwoken-info/runs/6646974514?check_suite_focus=true#step:12:979

**Comment by Flouse** [comment]
@jordanmack Shall we close this issue?

**Comment by jordanmack** [comment]
> @jordanmack Shall we close this issue?

Yes, the problem is resolved with the PR.
