### ISSUE TITLE
Testnetv1.1 godwoken-web3-prebuilds Error

### ISSUE THREAD

**Issue by masayil** [nervosnetwork/godwoken-info#31]
![image](https://user-images.githubusercontent.com/65291464/171772078-944a3cc3-f9b3-47ce-b23d-3f69d00628cb.png)
My images:
gw-readonly: ghcr.io/nervosnetwork/godwoken-prebuilds:v1.1.3-beta
web3:ghcr.io/nervosnetwork/godwoken-web3-prebuilds:1.1-rc-e574ece
web3-indexer:ghcr.io/nervosnetwork/godwoken-web3-indexer-prebuilds:1.1-rc-e574ece

I didn't modify anything except "gw-testnet_v1.1-config-readonly.toml"  and images.

**gw-testnet_v1.1-config-readonly.toml**
[rpc_client]
indexer_url = 'http://172.30.100.56:8116'
ckb_url = 'http://172.30.100.56:8114'

By the way, Will Testnetv0 be deprecated?

**Comment by Flouse** [comment]
1. Was the `gw-readonly` service healthy?
   Run `docker-compose ps` 
2. Testnetv0 will be deprecated. It is recommended to use the latest version of Godwoken testnet.
   https://github.com/nervosnetwork/godwoken-info#godwoken-public-network

**Comment by masayil** [comment]
I will try this #32  and give you feedback

**Comment by masayil** [comment]
> 1. Was the `gw-readonly` service healthy?
>    Run `docker-compose ps`
> 2. Testnetv0 will be deprecated. It is recommended to use the latest version of Godwoken testnet.
>    https://github.com/nervosnetwork/godwoken-info#godwoken-public-network

Hi. I'm using "info" branch.  so far so good.  I am waiting for `gw-readonly` to be ready. 
![image](https://user-images.githubusercontent.com/65291464/171910509-95d608d3-ba40-43b4-a786-7c33364ec333.png)

Once the `gw-readonly`  is ready, I will start Godwoken Web3 and web3-Indexer services. Then give you feedback

**Comment by masayil** [comment]
#32  It works
![image](https://user-images.githubusercontent.com/65291464/171971437-99ec9bb8-66c9-4b8e-ac68-3ab38be79f1f.png)
