### ISSUE TITLE
update bridged-token-list for Godowken testnet_v1

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/godwoken-info#44]
![image](https://user-images.githubusercontent.com/1297478/177342151-0f88761c-103e-42ee-9b93-9ef971403c62.png)
Some deployed sUDT_ERC20_Proxy [contracts](https://github.com/nervosnetwork/light-godwoken/blob/490c11e65f/src/light-godwoken/constants/tokens.ts#L56-L102) on [Godwoken testnet token bridge](https://testnet.bridge.godwoken.io/#/v1)

- [x] Add `testnet_v1/bridged-token-list.json` containing [UAN](https://github.com/nervosnetwork/rfcs/pull/335) and displayName
- [x] GwScan will register the above tokens to https://v1.testnet.gwscan.com/tokens/bridge

## References
- https://github.com/nervosnetwork/light-godwoken/blob/490c11e65f/src/light-godwoken/constants/tokens.ts#L56-L102
- https://github.com/nervosnetwork/godwoken-info/pull/41
- [mainnet_v1/bridged-token-list.json](https://github.com/nervosnetwork/godwoken-info/blob/rfc-uan/mainnet_v1/bridged-token-list.json)

**Comment by ShookLyngs** [comment]
提交了 PR:
- https://github.com/nervosnetwork/godwoken-info/pull/48
